language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    repo: DracoBlue/http-response-headers
    branch: master
    jdk: oraclejdk8
