language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/secring.gpg.enc -out ~/.gnupg/local.secring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/pubring.gpg.enc -out ~/.gnupg/local.pubring.gpg -d
deploy:
  - 
    provider: script
    script: .travis/deploy.sh
    on:
      repo: DracoBlue/http-response-headers
      branch: master
      jdk: oraclejdk8
  - 
    provider: script
    script: .travis/deploy.sh
    on:
      repo: DracoBlue/http-response-headers
      tags: true
      jdk: oraclejdk8
